#!/bin/bash
# postrm script for _-_PACKAGENAME_-_
#
# see: dh_installdeb(1)

set -e

#DEBHELPER#

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

. /usr/share/debconf/confmodule

__POSTRM.DB__

case "$1" in
    purge)
        __POSTRM.PURGE.DB__
    ;;
    remove)
    ;;
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0



