#! /bin/bash
# preinst script for _-_PACKAGENAME_-_
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
#
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

. /usr/share/debconf/confmodule

case "$1" in
    install)
        db_get _-_PACKAGENAME_-_/webroot
        if [ -z "$RET" ];then
            echo "You must specify a webroot"
            db_reset _-_PACKAGENAME_-_/webroot
            exit 1;
        fi
        hostname -f 2>&1 > /dev/null || { echo "Hostname seems broken. Aborting" >&2; exit 1; }
    ;;
    upgrade)
    ;;
    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


db_stop
exit 0
