#!/bin/bash
# prerm script for _-_PACKAGENAME_-_
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm
. /usr/share/packaged-site/_-_PACKAGENAME_-_/confmodule

# Run dbconfig-common
dbc_go _-_PACKAGENAME_-_ $@

case "$1" in
    remove|deconfigure)
        rm -f /etc/apache2/sites-enabled/110-_-_PACKAGENAME_-_-100-redirects.conf
        rm -f /etc/apache2/sites-available/110-_-_PACKAGENAME_-_-100-redirects.conf

        rm -f /etc/apache2/sites-enabled/110-_-_PACKAGENAME_-_-101-primary.conf
        rm -f /etc/apache2/sites-available/110-_-_PACKAGENAME_-_-101-primary.conf

        rm -f /etc/apache2/sites-enabled/110-_-_PACKAGENAME_-_-102-secondary.conf
        rm -f /etc/apache2/sites-available/110-_-_PACKAGENAME_-_-102-secondary.conf

        rm -f /etc/packaged-site/_-_PACKAGENAME_-_/apachedir
        rm -f /etc/packaged-site/_-_PACKAGENAME_-_/htpassd

        graceful_apache2;
    ;;
    upgrade)
    ;;
    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


