#!/bin/bash
# prerm script for _-_PACKAGENAME_-_
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

. /usr/share/debconf/confmodule

__PRERM.DB__

case "$1" in
    remove|deconfigure)

    rm -f /etc/packaged-site/_-_PACKAGENAME_-_/dynamic.yml
    rm -f /var/www/_-_PACKAGENAME_-_/app/_-_APPNAME_-_/config/dynamic.yml
    rm -f /var/www/_-_PACKAGENAME_-_/app/_-_APPNAME_-_/config/dynamic.yml.2
    rm -f /var/www/_-_PACKAGENAME_-_/app/_-_APPNAME_-_/config/dynamic.yml.3

__PRERM.WEB__

    ;;
    upgrade)
    ;;
    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


